version: '3.7'

services:
    
    dotnet:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - VARIANT=3.1
                - INSTALL_NODE=true
                - NODE_VERSION=lts/*
                - INSTALL_AZURE_CLI=false
        volumes:
            - ..:/workspace
        user: vscode
        command: sleep infinity

    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P@sS1W0Rd
            - MSSQL_PID=Express
        volumes:
            - ../data/mssql:/var/opt/mssql/data

